### PR TITLE
Functional Add profile GUI page

### PR DESCRIPTION
**Pull request by junjieteoh**
- [x] Functional add profile GUI page (with names, phone number, email, address, and tag)
- [X] Shifted logic of concatenation of profile text field into AddCommand to AddProfileWindow.fxml

Next steps 
- Beautify UI (especially stack pane placement)
- Add more profile fields (after v1.2)

### CODE REVIEW

**Review by 9teMare — CHANGES_REQUESTED** [review]
I think .fxml and .css file name should not be camel-cased, the first letter should be capitalized. Can you change at your end all the files under /resources/view/ to capitalize the first letter? So that later when we merge we don't need to resolve conflict. Other than that, LGTM.

**Comment by junjieteoh** [comment]
@9teMare I have changed the file names to what you requested and updated the JavaFX to 11 just like what you did in your other PR. Hopefully, it is ok now, can you please help me check again.

**Review by 9teMare — APPROVED** [review]
LGTM

**Comment by pnutzz-0207** [comment]
lgtm :)

**Review by pnutzz-0207 — APPROVED** [review]
lgtm :)

**Pull request merged**
